<?php

namespace AppBundle\Repository;

/**
 * asdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class asdRepository extends \Doctrine\ORM\EntityRepository
{
}
